/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ControllerBarang;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;


/**
 *
 * @author Anjar
 */
public class ViewBarang extends javax.swing.JInternalFrame {

    /**
     * Creates new form Costumer
     */
     ControllerBarang controller;
    public ViewBarang() {
        initComponents();
        controller = new ControllerBarang(this);
        controller.isiTable();
        controller.tampilurutan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtid = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        txtsatuan = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bupdate = new javax.swing.JButton();
        bdelete = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbbarang = new javax.swing.JTable();
        txtcari = new javax.swing.JTextField();
        BSearchC = new javax.swing.JButton();
        brefresh = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        txtharga = new javax.swing.JTextField();
        bsimpan = new javax.swing.JButton();
        txtstok = new javax.swing.JTextField();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(0, 204, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtid.setEditable(false);
        txtid.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtid.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtidMouseClicked(evt);
            }
        });
        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });
        txtid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtidKeyPressed(evt);
            }
        });
        jPanel1.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 250, 30));

        txtnama.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtnama.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamaActionPerformed(evt);
            }
        });
        jPanel1.add(txtnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 250, 30));

        txtsatuan.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtsatuan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtsatuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsatuanActionPerformed(evt);
            }
        });
        jPanel1.add(txtsatuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 250, 30));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Stok Barang");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 110, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("ID Barang");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 110, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Nama ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 110, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Satuan");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 110, 30));

        bupdate.setBackground(new java.awt.Color(255, 204, 0));
        bupdate.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        bupdate.setForeground(new java.awt.Color(255, 255, 255));
        bupdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/edit-icon.png"))); // NOI18N
        bupdate.setText("Update");
        bupdate.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bupdateActionPerformed(evt);
            }
        });
        jPanel1.add(bupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 330, 110, 40));

        bdelete.setBackground(new java.awt.Color(255, 51, 51));
        bdelete.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        bdelete.setForeground(new java.awt.Color(255, 255, 255));
        bdelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/trash-icon.png"))); // NOI18N
        bdelete.setText("Delete");
        bdelete.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdeleteActionPerformed(evt);
            }
        });
        jPanel1.add(bdelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 330, 100, 40));

        jPanel2.setBackground(new java.awt.Color(0, 204, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tbbarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbbarang.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tbbarangAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tbbarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbbarangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbbarang);

        txtcari.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcariActionPerformed(evt);
            }
        });
        txtcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcariKeyReleased(evt);
            }
        });

        BSearchC.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BSearchC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/search-icon.png"))); // NOI18N
        BSearchC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSearchCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(BSearchC, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtcari)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BSearchC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 520, 250));

        brefresh.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        brefresh.setForeground(new java.awt.Color(255, 255, 255));
        brefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Refresh-icon.png"))); // NOI18N
        brefresh.setText("Refresh");
        brefresh.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        brefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brefreshActionPerformed(evt);
            }
        });
        jPanel1.add(brefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, 130, 40));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-packing-25.png"))); // NOI18N
        jLabel6.setText("Data Barang");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 250, 40));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 930, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Harga");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 110, 30));

        txtharga.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtharga.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtharga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthargaActionPerformed(evt);
            }
        });
        jPanel1.add(txtharga, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 250, 30));

        bsimpan.setBackground(new java.awt.Color(0, 204, 255));
        bsimpan.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        bsimpan.setForeground(new java.awt.Color(255, 255, 255));
        bsimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/save-icon.png"))); // NOI18N
        bsimpan.setText("Simpan");
        bsimpan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsimpanActionPerformed(evt);
            }
        });
        jPanel1.add(bsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, 110, 40));

        txtstok.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtstok.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtstok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstokActionPerformed(evt);
            }
        });
        jPanel1.add(txtstok, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 250, 30));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbbarangAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tbbarangAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tbbarangAncestorAdded

    private void tbbarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbbarangMouseClicked
        // TODO add your handling code here:
        controller.isiField(tbbarang.getSelectedRow());
    }//GEN-LAST:event_tbbarangMouseClicked

    private void txtidMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtidMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidMouseClicked

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void txtidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidKeyPressed

    private void txtnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamaActionPerformed

    private void txtsatuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsatuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsatuanActionPerformed

    private void bupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bupdateActionPerformed
        // TODO add your handling code here:
        if (txtid.equals("")|txtharga.equals("")|txtnama.equals("")
           |txtsatuan.equals("")|txtstok.equals("")) {
           JOptionPane.showMessageDialog(rootPane, "Mohon Lengkapi Data ..!");
        }else{
            int confirmSimpan = JOptionPane.showConfirmDialog(rootPane,"Apakah anda yakin ingin Mengubah data dan data tersebut sudah benar?,"
                                                                        ,"Ubah data",JOptionPane.YES_NO_OPTION );
            if (confirmSimpan == JOptionPane.YES_OPTION){
        controller.update();
        controller.isiTable();
      txtharga.setText("");
        txtnama.setText("");
        txtid.setText("");
        txtsatuan.setText("");
        txtstok.setText("");
        controller.tampilurutan();
            }
        }
    }//GEN-LAST:event_bupdateActionPerformed

    private void brefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brefreshActionPerformed
        // TODO add your handling code here:
        txtharga.setText("");
        txtnama.setText("");
        txtid.setText("");
        txtsatuan.setText("");
        txtstok.setText("");
        controller.tampilurutan();
    }//GEN-LAST:event_brefreshActionPerformed

    private void BSearchCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSearchCActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_BSearchCActionPerformed

    private void bdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdeleteActionPerformed
        // TODO add your handling code here:
        if (txtid.equals("")|txtharga.equals("")|txtnama.equals("")
           |txtsatuan.equals("")|txtstok.equals("")) {
           JOptionPane.showMessageDialog(rootPane, "Mohon Lengkapi Data ..!");
        }else{
            int confirmSimpan = JOptionPane.showConfirmDialog(rootPane,"Apakah anda yakin ingin Hapus data,"
                                                                        ,"Hapus data",JOptionPane.YES_NO_OPTION );
            if (confirmSimpan == JOptionPane.YES_OPTION){
        controller.delete();
        controller.isiTable();
  txtharga.setText("");
        txtnama.setText("");
        txtid.setText("");
        txtsatuan.setText("");
        txtstok.setText("");
        controller.tampilurutan();
            }
        }
    }//GEN-LAST:event_bdeleteActionPerformed

    private void txtcariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcariKeyReleased
        // TODO add your handling code here:
       TableRowSorter<TableModel>sorter = new TableRowSorter<TableModel>(((DefaultTableModel)tbbarang.getModel()));
        sorter.setRowFilter(RowFilter.regexFilter(txtcari.getText().toString()));
        tbbarang.setRowSorter(sorter);
    }//GEN-LAST:event_txtcariKeyReleased

    private void txtcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcariActionPerformed

    private void txthargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthargaActionPerformed

    private void bsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsimpanActionPerformed
        // TODO add your handling code here:
        if (txtid.equals("")|txtharga.equals("")|txtnama.equals("")
           |txtsatuan.equals("")|txtstok.equals("")) {
           JOptionPane.showMessageDialog(rootPane, "Mohon Lengkapi Data ..!");
        }else{
            int confirmSimpan = JOptionPane.showConfirmDialog(rootPane,"Apakah anda yakin ingin Menyimpan data dan data tersebut sudah benar?,"
                                                                        ,"Simpan data",JOptionPane.YES_NO_OPTION );
            if (confirmSimpan == JOptionPane.YES_OPTION){
         controller.insert();
         txtharga.setText("");
        txtnama.setText("");
        txtid.setText("");
        txtsatuan.setText("");
        txtstok.setText("");
        controller.isiTable();
        
        controller.tampilurutan();
            }
        }
    }//GEN-LAST:event_bsimpanActionPerformed

    private void txtstokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstokActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BSearchC;
    private javax.swing.JButton bdelete;
    private javax.swing.JButton brefresh;
    private javax.swing.JButton bsimpan;
    private javax.swing.JButton bupdate;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tbbarang;
    private javax.swing.JTextField txtcari;
    private javax.swing.JTextField txtharga;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtsatuan;
    private javax.swing.JTextField txtstok;
    // End of variables declaration//GEN-END:variables
public JTextField getTxtIdBarang(){
    return txtid;
}

public JTextField getTxtNamaBarang(){
    return txtnama;
}
public JTextField getTxtSatuan(){
    return txtsatuan;
}
public JTextField getTxtHarga(){
    return txtharga;
}
public JTextField getTxtStok(){
    return txtstok;
}
public JTextField getTxtCari(){
    return txtcari;
}
public JTable getTableBarang(){
    return tbbarang;
}
}
